/**
 * Policy Content Configuration
 * 
 * This file contains all legal page content for milvia.ai.
 * To add, edit, or remove sections, simply modify the arrays below.
 * The UI will automatically reflect your changes.
 * 
 * Each section has:
 *   - id: A unique identifier (used for anchor links and table of contents)
 *   - title: The section heading displayed on the page
 *   - paragraphs: An array of text strings. Each string becomes a paragraph.
 *                  You can use simple HTML tags like <strong>, <em>, <a> for formatting.
 */

export const PRIVACY_POLICY_META = {
  title: 'Privacy Policy',
  effectiveDate: 'July 15, 2026',
  previousVersionDate: 'January 10, 2026',
};

export const PRIVACY_POLICY = [
  {
    id: 'introduction',
    title: '1. Introduction',
    paragraphs: [
      'milvia.ai ("we," "our," or "us") is an enterprise-grade Retrieval-Augmented Generation platform designed for processing technical manuals, contracts, and corporate documents. We are committed to protecting the privacy and security of your data.',
      'This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use the milvia.ai platform, including our web application, APIs, and related services (collectively, the "Services"). This policy does not apply to content that we process on behalf of customers under separate enterprise agreements.',
    ],
  },
  {
    id: 'information-we-collect',
    title: '2. Information We Collect',
    paragraphs: [
      '<strong>Account Information:</strong> When you register for an account, we collect your email address and authentication credentials through Firebase Authentication. We do not store passwords directly; authentication is managed by Google Firebase.',
      '<strong>Uploaded Documents:</strong> When you upload PDF documents for processing, we temporarily store the file content to parse, chunk, and generate vector embeddings. Document content is processed through our ingestion pipeline and indexed into your private vector store.',
      '<strong>Chat and Query Data:</strong> We collect the questions you ask through the chat interface and the responses generated by the system. This data is used solely to provide the retrieval and generation service to you.',
      '<strong>Usage and Log Data:</strong> We automatically collect standard server logs, including IP addresses, browser type, access times, and pages viewed. This information is used for security monitoring, performance optimization, and debugging.',
    ],
  },
  {
    id: 'how-we-use-information',
    title: '3. How We Use Your Information',
    paragraphs: [
      'We use the information we collect for the following purposes:',
      '• <strong>Service Delivery:</strong> To operate, maintain, and provide the core features of the milvia.ai platform, including document parsing, vector indexing, hybrid search, and AI-powered question answering.',
      '• <strong>Security and Fraud Prevention:</strong> To detect, investigate, and prevent unauthorized access, security incidents, and other malicious activities.',
      '• <strong>Service Improvement:</strong> To analyze usage patterns and optimize system performance, retrieval accuracy, and user experience.',
      '• <strong>Communication:</strong> To send you essential service notifications, security alerts, and account-related updates.',
    ],
  },
  {
    id: 'data-processing',
    title: '4. Document Processing and AI',
    paragraphs: [
      'When you upload documents to milvia.ai, the following processing occurs:',
      '• <strong>Parsing:</strong> Documents are parsed using the Docling pipeline to extract text, headers, tables, and structural metadata.',
      '• <strong>Chunking and Embedding:</strong> Extracted text is split into semantic chunks and converted into vector embeddings using third-party embedding models (such as Google Gemini or OpenAI). These embeddings are stored in your private Milvus vector database.',
      '• <strong>Query Processing:</strong> When you ask a question, your query is embedded and matched against your indexed documents using hybrid dense-sparse search. Relevant chunks are passed to a large language model (LLM) to generate a cited response.',
      '<strong>Important:</strong> Your uploaded documents and queries are never used to train any AI models. We use third-party LLM providers strictly through their non-training API endpoints.',
    ],
  },
  {
    id: 'data-storage',
    title: '5. Data Storage and Security',
    paragraphs: [
      'We implement industry-standard security measures to protect your data:',
      '• <strong>Encryption in Transit:</strong> All data transmitted between your browser and our servers is encrypted using TLS 1.2 or higher.',
      '• <strong>Encryption at Rest:</strong> Stored data, including vector embeddings and document metadata, is encrypted at rest.',
      '• <strong>Access Controls:</strong> Each user\'s document collection is isolated. You can only access documents and embeddings associated with your own authenticated account.',
      '• <strong>Infrastructure:</strong> Our services are hosted on secure cloud infrastructure with regular security audits and monitoring.',
    ],
  },
  {
    id: 'data-sharing',
    title: '6. Data Sharing and Third Parties',
    paragraphs: [
      'We do not sell, rent, or trade your personal information or document content to third parties. We share data only in the following limited circumstances:',
      '• <strong>AI Model Providers:</strong> Document chunks and queries are sent to third-party LLM and embedding providers (such as Google, OpenAI, Anthropic, or Voyage AI) solely for the purpose of generating embeddings and responses. These providers process data under their respective API terms, which prohibit using API inputs for model training.',
      '• <strong>Authentication Provider:</strong> Firebase Authentication (Google) processes your login credentials.',
      '• <strong>Legal Requirements:</strong> We may disclose information if required by law, regulation, legal process, or governmental request.',
    ],
  },
  {
    id: 'data-retention',
    title: '7. Data Retention and Deletion',
    paragraphs: [
      'We retain your data only for as long as necessary to provide the Services:',
      '• <strong>Account Data:</strong> Retained while your account is active. Upon account deletion, your data is removed within 30 days.',
      '• <strong>Uploaded Documents:</strong> Stored in your private vector index until you explicitly delete them through the application interface. Deletion removes both the document metadata and all associated vector embeddings from Milvus.',
      '• <strong>Chat History:</strong> Session-based chat data is not persisted beyond the active browser session unless explicitly saved.',
      '• <strong>Server Logs:</strong> Automatically purged after 90 days.',
      'You may request complete data deletion at any time by contacting us at <strong>privacy@milvia.ai</strong>.',
    ],
  },
  {
    id: 'your-rights',
    title: '8. Your Rights',
    paragraphs: [
      'Depending on your jurisdiction, you may have the following rights regarding your personal data:',
      '• <strong>Access:</strong> Request a copy of the personal data we hold about you.',
      '• <strong>Correction:</strong> Request correction of inaccurate or incomplete data.',
      '• <strong>Deletion:</strong> Request deletion of your personal data and all associated documents and embeddings.',
      '• <strong>Portability:</strong> Request a machine-readable export of your data.',
      '• <strong>Objection:</strong> Object to certain types of data processing.',
      'To exercise any of these rights, please contact us at <strong>privacy@milvia.ai</strong>. We will respond to your request within 30 days.',
    ],
  },
  {
    id: 'cookies',
    title: '9. Cookies and Local Storage',
    paragraphs: [
      'milvia.ai uses minimal browser storage technologies:',
      '• <strong>Authentication Tokens:</strong> Firebase session tokens are stored to maintain your login state.',
      '• <strong>Theme Preferences:</strong> Your light/dark mode preference is stored in localStorage.',
      '• <strong>Retrieval Settings:</strong> Your search configuration preferences (such as top-K results) are stored locally in your browser.',
      'We do not use advertising cookies or third-party tracking pixels.',
    ],
  },
  {
    id: 'changes',
    title: '10. Changes to This Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time to reflect changes in our practices, technology, or legal requirements. When we make material changes, we will notify you by updating the "Effective Date" at the top of this page and, where appropriate, providing additional notice through the application.',
      'We encourage you to review this Privacy Policy periodically to stay informed about how we protect your data.',
    ],
  },
  {
    id: 'contact',
    title: '11. Contact Us',
    paragraphs: [
      'If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:',
      '• <strong>Email:</strong> privacy@milvia.ai',
      '• <strong>Subject Line:</strong> Privacy Policy Inquiry',
      'We are committed to resolving any concerns about your privacy and will respond to all inquiries within 30 business days.',
    ],
  },
];

// =============================================================================
// ABOUT US CONTENT
// To edit the About Us page: add, remove, or modify sections below.
// =============================================================================

export const ABOUT_US_META = {
  title: 'About Us',
  subtitle: 'Building enterprise-grade document intelligence for technical teams.',
};

export const ABOUT_US = [
  {
    id: 'who-we-are',
    title: '1. Who We Are',
    paragraphs: [
      'milvia.ai is an enterprise-grade Retrieval-Augmented Generation (RAG) platform purpose-built for technical operations teams, engineering organizations, and safety-critical industries that rely on dense document libraries — including manuals, SOPs, contracts, and compliance specifications.',
      'We believe that the knowledge needed to make critical decisions is already written down somewhere. Our mission is to make that knowledge instantly searchable, verifiable, and actionable — no matter how large or complex the document library.',
    ],
  },
  {
    id: 'our-vision',
    title: '2. Our Vision',
    paragraphs: [
      'The gap between the volume of technical documentation that organizations produce and their teams\' ability to retrieve precise answers from it is enormous. Engineers spend hours searching through manuals. Safety reviewers scan hundreds of pages for a single specification. Operators lose critical time looking up procedure parameters under pressure.',
      'milvia.ai was built to close that gap. We envision a world where every technical team has an always-available, page-cited document assistant that retrieves verified answers in seconds — not hours.',
    ],
  },
  {
    id: 'core-technology',
    title: '3. Core Technology',
    paragraphs: [
      'milvia.ai is built on a production-grade open-source technology stack engineered for accuracy and reliability:',
      '• <strong>Structure-Aware Parsing (Docling):</strong> Our ingestion pipeline uses Docling to parse PDF documents while preserving their logical structure — including headers, section hierarchies, embedded tables, and image captions. This ensures that retrieved chunks remain contextually coherent and faithful to the original document layout.',
      '• <strong>Hybrid Dense-Sparse Search (Milvus + BM25):</strong> Queries are matched using a combination of dense semantic embeddings (powered by Gemini, OpenAI, or Voyage AI) and sparse BM25 keyword indices. This dual-channel approach ensures that both conceptually related answers and exact-keyword matches surface reliably, with results fused via Reciprocal Rank Fusion (RRF).',
      '• <strong>Cross-Encoder Reranking:</strong> Retrieved candidates are re-scored by a cross-encoder model that evaluates how well each chunk specifically answers the query — dramatically improving citation precision over traditional single-pass retrieval.',
      '• <strong>Asynchronous Ingestion Pipeline:</strong> Document uploads are queued and processed asynchronously using Redis and RQ workers, keeping the user interface responsive even during large document ingestion jobs.',
    ],
  },
  {
    id: 'built-for-trust',
    title: '4. Built for Trust',
    paragraphs: [
      'For teams operating in safety-critical and regulated environments, trust in the output is not optional — it is a core requirement.',
      '• <strong>Verified Citations:</strong> Every response includes page-level source references pointing back to the original document. Users can inspect the exact excerpt that generated each answer.',
      '• <strong>No Model Training on Your Data:</strong> Your uploaded documents and queries are never used to train or fine-tune any AI model. All third-party LLM and embedding calls are made through non-training API endpoints.',
      '• <strong>User-Isolated Data:</strong> Each user\'s document collection, embeddings, and query history are strictly isolated. No user can access another user\'s documents or retrieval results.',
      '• <strong>Transparent Operations:</strong> We are committed to maintaining clear documentation of how your data is collected, processed, stored, and deleted.',
    ],
  },
  {
    id: 'open-source',
    title: '5. Open Source Foundations',
    paragraphs: [
      'milvia.ai is built on a strong foundation of open-source technologies, including Milvus (vector database), Docling (document parsing), FastAPI (backend framework), and Redis (queue management). We believe in giving back to the communities that power our platform.',
      'We are grateful to the maintainers and contributors of these projects for making production-grade AI infrastructure accessible to all builders.',
    ],
  },
  {
    id: 'contact-us',
    title: '6. Get in Touch',
    paragraphs: [
      'We would love to hear from you — whether you are exploring milvia.ai for your team, have a technical question, or want to discuss an enterprise integration.',
      '• <strong>General Inquiries:</strong> hello@milvia.ai',
      '• <strong>Privacy & Data:</strong> privacy@milvia.ai',
      '• <strong>Enterprise Partnerships:</strong> enterprise@milvia.ai',
    ],
  },
];
